### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by hakandilek** [nooku/www.nooku.org#13]
Can you please provide a license file for the web site contents (layouts, posts, etc.).

**Comment by johanjanssens** [comment]
Hi, most happy to consider doing so. What license would have your preference and why ?

**Comment by hakandilek** [comment]
I'd suggest using the [MIT](http://choosealicense.com/licenses/mit/) because it's simple, requires a copyright notice for derivative work, and does not hold the owner liable. Please have a look at the [website root](http://choosealicense.com/) for more options.

My main intention was to build my own personal website on top of your Jekyll templates. They look really nice.

**Comment by johanjanssens** [comment]
Thanks @hakandilek We do not have any intend to make our Jekyll template for our site free software. The template is specifically build by us for the Nooku site and brand. There are a lot of free Jekyll templates our there already : http://jekyllthemes.org/ Hope that helps.
