### ISSUE TITLE
Add Community and Docs pages

### ISSUE THREAD

**Issue by robinpoort** [nooku/www.nooku.org#5]
Combine 'Guides' & 'API' on a 'Documentation' page and add a 'Community' page.

Also update the Bower dependencies to their latest maintenance releases.

**Comment by robinpoort** [comment]
@tomjanssens could you review this? Not 100% sure about the forums in the main menu because it links to a completely different page. With the guides and API you can at least navigate to the other pages easily. We might want to move this to the footer menu?

**Comment by tomjanssens** [comment]
Argeed, linking to external website in the main menu is a bad idea. Also, don't move the demo item to the main menu, just to much.

Idea: Combine 'Guides' & 'API' on a 'Documentation' page and add a 'Community' page.

![screenshot 2015-02-12 16 11 45](https://cloud.githubusercontent.com/assets/700063/6170162/d92db514-b2d2-11e4-9824-764504282df1.png)

**Comment by johanjanssens** [comment]
Agreed. The idea of having the forums more visible is to allow people to find it. Right now that is pretty hard, if you do not know where to look. I like the idea of having a 'community' page where we can list all community resources.

**Comment by tomjanssens** [comment]
Changed the description to reflect our new idea.

**Comment by tomjanssens** [comment]
Deployed:
- http://www.nooku.org/community/
- http://www.nooku.org/docs/

@johanjanssens can you verify?

**Comment by johanjanssens** [comment]
Verified, all good.

On Fri, Feb 13, 2015 at 6:25 PM, Tom Janssens notifications@github.com
wrote:

> Deployed:
> - http://www.nooku.org/community/
> - http://www.nooku.org/docs/
> 
> @johanjanssens https://github.com/johanjanssens can you verify?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nooku/www.nooku.org/issues/5#issuecomment-74291217.

## 

[image: --]

Johan Janssens
[image: http://]about.me/johanjanssens
http://about.me/johanjanssens?promo=email_sig
