### ISSUE TITLE
[blog] Nooku as backend to Client Applications

### ISSUE THREAD

**Issue by magneticmg** [nooku/www.nooku.org#7]
Blog post about using Nooku as backend to Client Applications.

**Comment by daveli** [comment]
I'm currently working on a AngularJS app using Nooku (Framework) for the backend, so I might be able to help out with this blog post.

**Comment by magneticmg** [comment]
Dave! Awesome. I want to hook up with you on this. I've written several app pieces using Backbone.js and tied the models/collections to item/items attributes of the response json in v1.0 of the framework. 

I'll come up with an outline of what I think would make a good post and get you to comment. Then we can start filling it in. If you have any ideas before I get to it, go ahead and list them in the description here or in a Google doc and share it with me.

**Comment by Klaasvaak** [comment]
At Moyoweb we use Nooku Platform with an ember.js app. If we can contribute to this post let us know.

**Comment by johanjanssens** [comment]
@Klaasvaak Definitely. Seems we have three JS apps being used. Angular JS, Backbone.js and Ember.js. I suggest that we do either a blog post with basic info on all three or we make it three separate posts. 

I suggest that everyone tries to write ip a draft post in Google Docs and then we take it from there ?

**Comment by Klaasvaak** [comment]
@johanjanssens Sounds good. I will write a short text on how we use it. We are still planning to write a full blog post about ember.js with Nooku Platform.

**Comment by johanjanssens** [comment]
@Klaasvaak Excellent.

**Comment by magneticmg** [comment]
Hey All, 

I have been thinking about this post a fair bit over the past week. I think I have a good framework for how to move forward. 

@johanjanssens , yes I think that's a good tact to take, but I think we can focus each other's efforts a little. So here are some 'business rules' for the post:

## Introduction

Motivation and current state of this practice. A bit about what we are doing in the post. 

## The Nooku Todo Component

This is to be the 'service' we are interacting with. Combined with the Vagrant box, composer, etc. Everyone has the same beast. 

## TodoMVC

This is a great thing :) . It should give us a common interface, and solid working code for a Todo blog post. It will let each of us focus on the specifics of how to tie our Todo component into each libraries persistence apparatus. (I have a copy of the Backbone example http://todomvc.com/examples/backbone/ ). The other sections http://todomvc.com/examples/emberjs/ and http://todomvc.com/examples/emberjs/ and http://todomvc.com/examples/angularjs/#/ are there. The code is there, which we can just grab and show where we make our additions. 

## The Nitty-Gritty

### Ember.js

### Angular.js

### Backbone.js
- tie the url of the into the collections
- account for the slight difference in JSON format from the service (Backbone wants what we return as the entity/entities property) 
- handle token and auth in someway (serving the application as a component view would take care of this nicely).
  _That's pretty much it from the backbone end._

This could be one larger post or a series of 3 shorter posts. 

I'd love some thoughts. Thanks!

**Comment by tomjanssens** [comment]
Let's keep the ticket open until the blog post is published.

**Comment by magneticmg** [comment]
That's a fine idea. Sorry guys, closed by accident.

**Comment by johanjanssens** [comment]
@cameron excellent suggestions. Nothing to add.

On Sun, Mar 1, 2015 at 3:56 PM, Cameron Barr notifications@github.com
wrote:

> That's a fine idea. Sorry guys, closed by accident.
> On Mar 1, 2015 9:48 AM, "Tom Janssens" notifications@github.com wrote:
> 
> > Let's keep the ticket open until the blog post is published.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/nooku/www.nooku.org/issues/7#issuecomment-76599852.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nooku/www.nooku.org/issues/7#issuecomment-76600232.

## 

[image: --]

Johan Janssens
[image: http://]about.me/johanjanssens
http://about.me/johanjanssens?promo=email_sig

**Comment by magneticmg** [comment]
Hi All, 
In support of this blog post I've incorporated the backbone portion of TodoMVC and made the necessary edits to get it to work with Nooku as the data backend. 

There are lots of approaches that could be taken, but I decided to make it all part of our Joomla-todo package. This is forked on my github https://github.com/magneticmg/joomla-todo/tree/feature/7-backbone. Rationale being that anyone can use the vagrant box to spin up a site, checkout this branch in there Project directory and symlink as I have done and would explain in the post.

For reference: 

`$ cd Projects;
$ git clone https://github.com/magneticmg/joomla-todo/`
`$ joomla site:create todo --joomla=3.2 --symlink=joomla-todo
 // 3.2 was what was working at the time`

> _Because this is a post about Nooku, where possible I talk about/work examples to showcase the versatility of the framework, to fit into what the client library needs_

## Site

### Responses

 Backbone expects collections to be returned from the server as a json array of models (json objects). It also expects singular items to be returned as plain json objects (without the JSON API spec meta, limits, etc). To provide that response I wrote a simple view behavior called 'backbone', that sets the $view::_content before.render..

### Structure

I've added a view to the component simply called **app** and the matching controller (could make it the default controller in the dispatcher). The controller extends KControllerView. I have used the `default.html.php` file as the backbone representation. Other layouts could be `ember.html.php` and `angular.html.php`, for example if we were to include examples all in the same branch, otherwise these other two examples would be the default.html.php files in respective ember branches. 
I have also made a slight change to the router.php file, so that com_todo works even when there is no menu item assigned to it. 

## Media

All of the app assets (javascript and css) are in media/com_todo/backbone unless they are identified as common to all TodoMVC examples. In that case there are in the media/com_todo/ folder prefixed with 'todomvc-' . The idea being that there could be media/com_todo/ember and media/com_todo/angular for other examples.

## Specific Javascript/Nooku Needs

Models and collections work via url related properties or methods (or localstorage namespace instead) to know where to request from. In the Todos collection the only change needed was that I specify the `url` property to  `/component/todo/items`. Similarly, the Todo model needed only the `urlRoot` property to be specified to `/component/todo/item/`

### Backbone Templates (_underscore.js)

To get these to show up properly with our script filter, `data-inline` needs to go in front of the `type="text/template"`. 

### Dealing with csrf tokens.

I simply tied a `beforeSend` callback to `Backbone.$` via `ajaxSetup` and tie the token to the data for each request where data is being sent to the server. 

## Closing Notes

I think the point of the post is to showcase the retrieving and saving of data using Nooku as the backend. So, that means we can strip out a lot of the functionality showcased in TodoMVC to keep it simple. If you guys have any notes about the structure of the example or concepts you think should go in then shout it out. 

# Thanks !

p.s. I should also add that I have been working with the app with the following URL

http://todo.dev/component/todo/app/?tmpl=component&tempate=system

**Comment by magneticmg** [comment]
I have ended up breaking this up into a blog post and a more in depth Tutorial piece that would go into the Guides.

**Blog Post:**

https://docs.google.com/document/d/1I_vGB-MO1yQEwUBoIZLMGJdaBmjvlrt52BEXD1E3cVo/edit?usp=sharing

**Tutorial/Topical Guide**

https://docs.google.com/a/timble.net/document/d/1Rq_fu2qAQ7-R9i9bC84KegYAXuDGO5uzDqVZNI_MeB4/edit?usp=sharing 

Any comments and suggested edits are welcome. We could potential run follow up Blog posts with Ember and Angular, or include some specifics about persisting data for either of them. 

Thanks!

**Comment by johanjanssens** [comment]
@magneticmg Reviewed both and left comments.

**Comment by tomjanssens** [comment]
Blog post published: http://www.nooku.org/blog/2015/06/backbone-joomla-and-nooku-an-instant-friendship/
